name: Generate Snake Animation

on:
  # run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # allows to manually run the job at any time
  workflow_dispatch:
    
  # run on every push to the master or main branch
  push:
    branches:
      - master
      - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Checks out your repository so the action can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Generates the snake animation SVGs
      - name: Generate Snake SVGs
        uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Pushes the generated files to an 'output' branch
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
